### ISSUE TITLE
When you create a room with player1 and both players join and then player1 reloads the page and if the player2 reloads the page it gives this error

### ISSUE THREAD

**Issue by Sid1512** [codingexpert1999/rock-paper-scissors#1]
![image](https://user-images.githubusercontent.com/46813781/128556644-ad479ff2-e7f9-4027-b6dc-8f25a7021246.png)

**Comment by codingexpert1999** [comment]
When you reload the page the socket disconnect event is emmited which is going to call the exitRoom function. So if you reload the page as the first player the exitRoom function deletes the room and thats why you are getting this error because you are trying to set a value on something that doesn't exist.

**Comment by codingexpert1999** [comment]
If you can't debug your error send me a folder with your work so far in the email codingexpert1999@gmail.com and I will try to debug it.

**Comment by Sid1512** [comment]
Yeah i fixed it now, thanks!

**Comment by Sid1512** [comment]
This is the code i used to fix
const exitRoom = (roomId, player) => {
    if (player === 2) {
        rooms[roomId][1] = "";
    } else {
        delete rooms[roomId];
    }
}
